#!/bin/sh
# This is a comment!
echo Hello World    # This is a comment, too!
chmod 755 first.sh
./first.sh
Hello World

#!/bin/sh
# This is a comment!
echo "Hello   World"    # This is a comment, too!
