#!/bin/sh
# This is a comment!
echo Hello World    # This is a comment, too!
chmod 755 first.sh
./first.sh
Hello World

#!/bin/sh
# This is a comment!
echo "Hello   World"    # This is a comment, too!

#!bin/sh
# This is a comment!
echo "Hello   World"    # This is a comment, too!
echo "Hello World"
echo "Hello * World"
echo Hello * World
echo Hello    World
echo "Hello" World
echo Hello "    " World
echo "Hello "*" World"
echo `hello` world
echo 'hello' world
