#!/bin/sh
MY_MESSAGE="Hello World"
echo $MY_MESSAGE

MY_MESSAGE="Hello World"
MY_SHORT_MESSAGE=hi
MY_NUMBER=1
MY_PI=3.142
MY_OTHER_PI="3.142"
MY_MIXED=123abc

#!/bin/sh
echo What is your name?
read MY_NAME
echo "Hello $MY_NAME - hope you're well."

#!/bin/sh
echo "MYVAR is: $MYVAR"
MYVAR="hi there"
echo "MYVAR is: $MYVAR"

$ ./myvar2.sh
MYVAR is:
MYVAR is: hi there

$ MYVAR=hello
$ ./myvar2.sh
MYVAR is:
MYVAR is: hi there

$ export MYVAR
$ ./myvar2.sh
MYVAR is: hello
MYVAR is: hi there

$ echo $MYVAR
hello
$

$ MYVAR=hello
$ echo $MYVAR
hello
$ . ./myvar2.sh
MYVAR is: hello
MYVAR is: hi there
$ echo $MYVAR
hi there

#!/bin/sh
echo "What is your name?"
read USER_NAME
echo "Hello $USER_NAME"
echo "I will create you a file called $USER_NAME_file"
touch $USER_NAME_file
